# Known Issues

## Known issues with the climr app :(

This section is focused on aspects of the climr App related to
trade-offs and intrinsic sources of error. We also list bugs or minor
enhancements that have not yet been resolved. If you have a problem or
suggestion to report, you can enter it as a "New issue" in our
<a href="https://github.com/bcgov/climr-app/issues" target="_blank">GitHub
repo </a>.

### Issues requiring fixing

- Viewing a Time Series plot for a single map point in the **Visualization** tab currently can take up to a minute. This is because the app downscales data for the recommended GCMs and SSPs, and all climate variables to create an interactive plot. We currently do not have a way to improve the time it takes to downscale the data.

- If a user attempts to downscale data from a drawn area or uploaded shape file in the **Get Data** tab with the recommended defaults selected for Simulated Climate Data, max runs specified and multiple extra climate variables or variable packages selected, the process can overwhelm the amount of memory available on our server. We are currently working on ways to address this issue.

- For raster downscaling in the **Get Data** tab, there are limits set on the job size based on the estimated number of output raster layers. If a user wants a higher resolution than is available given the input parameters, we recommend either running the downscale process one GCM at a time or one variable at a time, as this will decrease the number of output raster layers. We are currently working on ways to address this issue.

- In the **Get Data** tab, if a user downscales with shape data input but selects csv output, downscale runs that have a large number of variable combinations (raster layers) will take a few minutes to be converted into a useful csv format. We are working on speeding this up.

- In the **Visualization** tab, the 1961-1990 baseline for Continentality (TD) in the Time Series plots (the dashed line) is incorrect. This is likely inherent in the calculation of TD.

- In the **Visualization** tab, we are missing time series data for some ecoregions. We are working on this!